{% set name = "tiffslide" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 209653e86c75da29d7d3dbc21f2d0075b997e4e42bcb958dc4c8c8301786882a

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - backports.cached-property  # [py<38]
    - fsspec
    - imagecodecs
    - importlib-metadata  # [py<38]
    - pillow
    - python
    - tifffile >=2020.9.22
    - typing-extensions  # [py<38]
    - zarr  # [py>37]
    - zarr <2.11.0  # [py<38]

test:
  imports:
    - tiffslide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bayer-science-for-a-better-life/tiffslide
  summary: A drop-in replacement for openslide-python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - sarthakpati
    - sdvillal
